name: Max T0 Sell Impact
description: Price impact of largest T0 sell trade (bps)
tableName: dex_latest_metrics
updatedAt: "2026-02-21T06:00:00.000Z"
metricQuery:
  exploreName: dex_latest_metrics
  dimensions: []
  metrics:
    - dex_latest_metrics_max_swap_t0_in_impact
  filters:
    dimensions:
      id: c0000006-0000-0000-0000-000000000001
      and:
        - id: c0000006-0000-0000-0000-000000000002
          target:
            fieldId: dex_latest_metrics_protocol
          values:
            - orca
          operator: equals
          required: false
        - id: c0000006-0000-0000-0000-000000000003
          target:
            fieldId: dex_latest_metrics_pair
          values:
            - USX-USDC
          operator: equals
          required: false
  sorts: []
  limit: 1
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: big_number
  config:
    selectedField: dex_latest_metrics_max_swap_t0_in_impact
    label: "Max T0 Sell Impact (bps)"
    showBigNumberLabel: true
pivotConfig:
  columns: []
slug: kpi-max-sell-impact
tableConfig:
  columnOrder:
    - dex_latest_metrics_max_swap_t0_in_impact
spaceSlug: shared
version: 1
